services:
  safedeal:
    build: .
    container_name: safedeal-app
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      APP_URL: "http://194.32.141.214:8001"
    volumes:
      - safedeal_data:/data

volumes:
  safedeal_data:
